### ISSUE TITLE
JavaScript COnsole Errors in Event_galley.html page

### ISSUE THREAD

**Issue by Aryan-Lokhande-17** [Aryan-Lokhande-17/Morya-Caterers#1]
Please try and solve the errors in the Java script

**Comment by MaxVon89** [comment]
Will try...

**Comment by Aryan-Lokhande-17** [comment]
> Will try...

Uncaught TypeError: Cannot set properties of null (setting 'innerText')
    at HTMLDivElement.<anonymous> (main.js:139:34)

**Comment by MaxVon89** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Unexpected_type
Still on it.
